import type { Metadata } from 'next';
import { Golos_Text } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/widgets';
import localFont from 'next/font/local';
import { AuthProvider } from '@/shared/providers/AuthProvider';

const golosText = Golos_Text({
  variable: '--font-golos-text',
  subsets: ['latin'],
});

const customFont = localFont({
  src: '../../public/fonts/druktextwidecyr-medium.woff2',
  variable: '--font-druk', // CSS переменная
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golosText.variable} ${customFont.variable} antialiased h-screen overflow-x-hidden`}
      >
        <AuthProvider>
          <Header />
          <main className={'w-full font-druk'} id={'main'}>
            {children}
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
